---
# Copyright 2024 Laurence Alexander Hurst
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
- name: Hostfile ipv4 entries are correct for hosts
  become: true
  ansible.builtin.lineinfile:
    path: '{{ hosts_file_path }}'
    line: "{{ item.ipv4.address }}\t{{ item.hostname }}{% if item.add_short_name | default(true) and '.' in item.hostname %}\t{{ item.hostname.split('.', 1) | first }}{% endif %}{% if 'aliases' in item.ipv4 %}\t{{ item.ipv4.aliases | join('\t') }}{% endif %}"
    regexp: '^{{ item.ipv4.address }}\s'
  loop: '{{ hosts_file_hosts }}'
  when: "'ipv4' in item"
- name: Hostfile ipv6 entries are correct for hosts
  become: true
  ansible.builtin.lineinfile:
    path: '{{ hosts_file_path }}'
    line: "{{ item.ipv6.address }}\t{{ item.hostname }}{% if item.add_short_name | default(true) and '.' in item.hostname %}\t{{ item.hostname.split('.', 1) | first }}{% endif %}{% if 'aliases' in item.ipv6 %}\t{{ item.ipv6.aliases | join('\t') }}{% endif %}"
    regexp: '^{{ item.ipv6.address }}\s'
  loop: '{{ hosts_file_hosts }}'
  when: "'ipv6' in item"
- name: No incorrect hosts for configured hostnames
  become: true
  ansible.builtin.lineinfile:
    path: '{{ hosts_file_path }}'
    regexp: '^(?!{{ valid_addresses | join("|") }})[^\s]+\s(?:.*\s)*(?:{{ item.hostname }}{% if item.add_short_name | default(true) and "." in item.hostname %}|{{ item.hostname.split(".", 1) | first }}{% endif %}{% if aliases | length > 0 %}|{{ aliases | join("|") }}{% endif %})(\s|$)'
    state: absent
  loop: '{{ hosts_file_hosts }}'
  vars:
    valid_addresses: >-
      {{
        item
        | dict2items
        | selectattr('key', 'in', ['ipv4', 'ipv6'])
        | map(attribute='value')
        | map(attribute='address')
      }}
    aliases: >-
      {{
        item
        | dict2items
        | selectattr('key', 'in', ['ipv4', 'ipv6'])
        | map(attribute='value')
        | selectattr('aliases', 'defined')
        | map(attribute='aliases')
        | flatten
      }}
...
